// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2r8NDc0SP8YABD1-lljWs_WtSmV1MoFk',
    appId: '1:821474654425:web:82bd79764a7a438cfda6c8',
    messagingSenderId: '821474654425',
    projectId: 'click-shop-d62ad',
    authDomain: 'click-shop-d62ad.firebaseapp.com',
    storageBucket: 'click-shop-d62ad.firebasestorage.app',
    measurementId: 'G-7VD2HJYGKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMIl-aOzJaS2d29-ocCRXakCsIhnlrCn0',
    appId: '1:821474654425:android:90fbf0b4ea10db2cfda6c8',
    messagingSenderId: '821474654425',
    projectId: 'click-shop-d62ad',
    storageBucket: 'click-shop-d62ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtth_Y26QmKO_fw-zbIaui3DujglmUWMI',
    appId: '1:821474654425:ios:1f5b92bc4f941e28fda6c8',
    messagingSenderId: '821474654425',
    projectId: 'click-shop-d62ad',
    storageBucket: 'click-shop-d62ad.firebasestorage.app',
    iosBundleId: 'com.example.clickShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtth_Y26QmKO_fw-zbIaui3DujglmUWMI',
    appId: '1:821474654425:ios:1f5b92bc4f941e28fda6c8',
    messagingSenderId: '821474654425',
    projectId: 'click-shop-d62ad',
    storageBucket: 'click-shop-d62ad.firebasestorage.app',
    iosBundleId: 'com.example.clickShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2r8NDc0SP8YABD1-lljWs_WtSmV1MoFk',
    appId: '1:821474654425:web:d676c165b1e21709fda6c8',
    messagingSenderId: '821474654425',
    projectId: 'click-shop-d62ad',
    authDomain: 'click-shop-d62ad.firebaseapp.com',
    storageBucket: 'click-shop-d62ad.firebasestorage.app',
    measurementId: 'G-WGZ3CW0DML',
  );
}
