/**
 * ClickShop — Crawler Search Proxy (Cloudflare Worker).
 *
 * Sits in front of the web host and solves the "white-screen" problem:
 * search crawlers (Googlebot, Bingbot, ...) don't wait for the Flutter
 * Wasm/Skwasm engine to boot, so they need instant, fully-rendered HTML.
 *
 * Behaviour:
 *   - Real humans  -> passthrough to the high-performance Wasm app (origin).
 *   - Search bots  -> served a pre-cached, fully-rendered HTML snapshot
 *                     (generated by tools/prerender.mjs) from the
 *                     PRERENDER_BASE_URL, with a fallback to origin.
 *
 * Deploy:
 *   wrangler deploy
 * then proxy your domain (DNS) through this Worker and point ORIGIN at your
 * Firebase/Cloudflare Pages site.
 */

// Defaults — override via Worker env vars (ORIGIN, PRERENDER_BASE_URL).
const DEFAULT_ORIGIN = 'https://click-shop-d62ad.web.app';
const DEFAULT_PRERENDER_BASE_URL = 'https://click-shop-prerender.web.app';

const BOT_RE =
  /googlebot|bingbot|slurp|duckduckbot|baiduspider|yandexbot|sogou|exabot|facebookexternalhit|facebot|twitterbot|whatsapp|telegrambot|vkShare|pinterest|redditbot|linkedinbot|embedly|quora link preview|ia_archiver|curl|wget|headless/i;

// Assets that are never pre-rendered (Flutter build output, images, fonts...).
const STATIC_RE = /\.(?:js|mjs|css|wasm|png|jpe?g|gif|webp|svg|ico|ttf|otf|woff2?|json|txt|xml|map)$/i;

export default {
  async fetch(request, env) {
    const ORIGIN = env.ORIGIN || DEFAULT_ORIGIN;
    const PRERENDER_BASE_URL =
      env.PRERENDER_BASE_URL || DEFAULT_PRERENDER_BASE_URL;

    const url = new URL(request.url);
    const userAgent = request.headers.get('user-agent') || '';
    const isBot = BOT_RE.test(userAgent);
    const isStatic = STATIC_RE.test(url.pathname);

    // Security headers: mandatory for multi-threaded Wasm/Skwasm rendering.
    const securityHeaders = {
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'credentialless',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'SAMEORIGIN',
      'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
    };

    // Static assets pass straight through for everyone.
    if (isStatic) {
      const passthrough = await fetch(`${ORIGIN}${url.pathname}${url.search}`, request);
      return new Response(passthrough.body, {
        status: passthrough.status,
        headers: new Headers({
          ...Object.fromEntries(passthrough.headers),
          ...securityHeaders,
        }),
      });
    }

    // Crawlers: try the pre-rendered snapshot first.
    if (isBot) {
      const snapshotUrl = `${PRERENDER_BASE_URL}${toSnapshotPath(url.pathname)}`;
      const snapshot = await fetch(snapshotUrl, request);
      if (snapshot.ok) {
        return new Response(snapshot.body, {
          status: 200,
          headers: new Headers({
            'Content-Type': 'text/html; charset=utf-8',
            ...securityHeaders,
            'X-Robots-Tag': 'index, follow, max-image-preview:large',
            'Cache-Control': 'public, max-age=3600',
          }),
        });
      }
      // Fall through to origin if no snapshot exists yet.
    }

    // Humans (and bots without a snapshot): the real app, with security
    // headers still applied so Wasm can boot.
    const originResponse = await fetch(`${ORIGIN}${url.pathname}${url.search}`, request);
    const responseHeaders = new Headers(originResponse.headers);
    Object.entries(securityHeaders).forEach(([k, v]) => responseHeaders.set(k, v));
    if (isBot) {
      responseHeaders.set('X-Robots-Tag', 'index, follow');
    }
    return new Response(originResponse.body, {
      status: originResponse.status,
      headers: responseHeaders,
    });
  },
};

/** /products/abc -> /products/abc/index.html ; / -> /index.html */
function toSnapshotPath(pathname) {
  if (pathname === '/' || pathname === '') return '/index.html';
  const clean = pathname.replace(/\/+$/, '');
  return `${clean}/index.html`;
}
